"""empty message

Revision ID: ac6e1b2c475b
Revises: fd71835914d6
Create Date: 2020-05-13 14:25:50.364832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6e1b2c475b'
down_revision = 'fd71835914d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    # op.execute(INSERT todolists  (name) VALUES ('Uncategorized');)
    #op.execute('UPDATE  todos SET list_id=1 WHERE list_id IS NULL;')
    #op.alter_column('todos', 'list_id', nullable=False)
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
