"""empty message

Revision ID: fd71835914d6
Revises: 53f946dccbe2
Create Date: 2020-05-13 09:27:29.706012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd71835914d6'
down_revision = '53f946dccbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # We have some changes to work with existing data
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # Updated null values
    op.execute('UPDATE  todos SET completed = False WHERE completed IS NULL;')
    # Updated column to value != null
    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
